/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

/**
 *
 * @author Vinicius
 */

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class NewJFrame extends javax.swing.JFrame {

    DefaultTableModel DTM;
    Conexao C;
    
    public NewJFrame() {
        initComponents();
        Color Background = new Color(194,211,211);
        getContentPane().setBackground(Background);
        
        C = new Conexao();
        
        DTM = new DefaultTableModel();
        DTM.addColumn("Código");
        DTM.addColumn("Marca");
        DTM.addColumn("Modelo");
        DTM.addColumn("Cor");
        DTM.addColumn("Tipo de Gás");
        DTM.addColumn("Potência BTU");
        DTM.addColumn("Tempo de Garantia");
        DTM.addColumn("Voltagem");
        
        Ares.setModel(DTM);
        
        MostrarDados();
    }

    
    void MostrarDados()
    {
        while (DTM.getRowCount() > 0)
        {
            DTM.removeRow(0);
        }
            
        try
        {
                C.setResultSet("Select * from arcondicionado");
                if (C.getResultSet().first() == true)
                {
                    do
                    {
                        DTM.addRow
                        (
                            new Object[]
                            {
                                C.getResultSet().getString("CodArCondicionado"),
                                C.getResultSet().getString("Marca"),
                                C.getResultSet().getString("Modelo"),
                                C.getResultSet().getString("Cor"),
                                C.getResultSet().getString("TipoGas"),
                                C.getResultSet().getString("PotenciaBTU"),
                                C.getResultSet().getString("TempoGarantia"),
                                C.getResultSet().getString("Voltagem")
                            }
                        
                        );
                    }
                    while (C.getResultSet().next() == true);
                }
        }
        catch (Exception E){}
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        Modelo = new javax.swing.JTextField();
        Cor = new javax.swing.JTextField();
        Gas = new javax.swing.JTextField();
        BTU = new javax.swing.JTextField();
        Voltagem = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ares = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Garantia = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Voltagem:");

        Voltagem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "127", "220" }));
        Voltagem.setSelectedIndex(-1);

        jButton1.setText("CADASTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXCLUIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("GERENCIAMENTO DE AR CONDICIONADOS");

        Ares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Ares);

        jLabel2.setText("Marca:");

        jLabel3.setText("Cor:");

        jLabel4.setText("Modelo:");

        jLabel5.setText("Tipo de Gás:");

        jLabel6.setText("Tempo de Garantia (Anos):");

        jLabel7.setText("Potência BTU:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Marca))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Gas))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Garantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTU))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Voltagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(Cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Gas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(BTU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(Garantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(Voltagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Mensagem = "";
        int Cont = 0;
        boolean Continuar = true;

        if (Marca.getText().isEmpty() == true)
        {
            Mensagem += "\nMarca (Vazio)";
            Marca.requestFocus();
            Cont++;
        }
        if (Modelo.getText().isEmpty() == true)
        {
            Mensagem += "\nModelo (Vazio)";
            Modelo.requestFocus();
            Cont++;
        }
        if (Cor.getText().isEmpty() == true)
        {
            Mensagem += "\nCor (Vazio)";
            Cor.requestFocus();
            Cont++;
        }
        if (Gas.getText().isEmpty() == true)
        {
            Mensagem += "\nTipo de Gás (Vazio)";
            Gas.requestFocus();
            Cont++;
        }
        if (BTU.getText().isEmpty() == true)
        {
            Mensagem += "\nPotência de BTU (Vazio)";
            BTU.requestFocus();
            Cont++;
        }
        try
        {
            float Pot_BTU = Integer.parseInt(BTU.getText());
        }
        catch (NumberFormatException E)
        {
            Mensagem += "\nPotência de BTU (Insira um valor Inteiro)";
            Voltagem.requestFocus();
            Cont++;
        }
        if (Voltagem.getSelectedIndex() == -1)
        {
            Mensagem += "\nVoltagem (Vazio)";
            Voltagem.requestFocus();
            Cont++;
        }
        if (Integer.parseInt(String.valueOf(Garantia.getValue())) < 0)
        {
            Mensagem += "\nGarantia (Maior ou igual a 0)";
            Garantia.requestFocus();
            Cont++;
        }

        if (Cont > 1)
        {
            Mensagem = "Por Favor, Corrija os Campos de: " + Mensagem;
            Continuar = false;
            JOptionPane.showMessageDialog(this, Mensagem, "AVISO", 2);
        }
        else if (Cont == 1)
        {
            Mensagem = "Por Favor, Corrija o Campo de: " + Mensagem;
            Continuar = false;
            JOptionPane.showMessageDialog(this, Mensagem, "AVISO", 2);
        }

        if(Continuar)
        {

            String SQL = " INSERT INTO arcondicionado (Marca, Modelo, Cor, TipoGas, PotenciaBTU, TempoGarantia, Voltagem) " +
            " VALUES ( " +
            " '" + Marca.getText() + "', " +
            " '" + Modelo.getText() + "', " +
            " '" + Cor.getText() + "', " +
            " '" + Gas.getText() + "', " +
            " '" + BTU.getText() + "', " +
            " '" + Garantia.getValue() + "', " +
            " '" + Voltagem.getSelectedItem()+ "' " +
            " ) ";

            C.SQLExecute(SQL);

            MostrarDados();

            Ares.setModel(DTM);

            JOptionPane.showMessageDialog(this, "Ar Condicionado Cadastrado com Sucesso", "AVISO", 1);

            Marca.setText("");
            Modelo.setText("");
            Cor.setText("");
            Gas.setText("");
            BTU.setText("");
            Garantia.setValue(0);
            Voltagem.setSelectedIndex(-1);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (DTM.getRowCount()>0)
        {
            if (Ares.getSelectedRowCount() > 0)
            {
                if (JOptionPane.showConfirmDialog(this, "Deseja Deletar o Ar Condicionado "
                    + Ares.getValueAt(Ares.getSelectedRow(), 1)
                    + " Modelo " + Ares.getValueAt(Ares.getSelectedRow(), 2), "AVISO", 0) == 0)
            {
                String SQL;
                SQL = "DELETE FROM arcondicionado WHERE CodArCondicionado = "
                + (Ares.getValueAt(Ares.getSelectedRow(), 0));

                C.SQLExecute(SQL);

                JOptionPane.showMessageDialog(this, "Ar Condicionado Deletado com Sucesso");

                MostrarDados();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Selecione uma linha da tabela para Deletar", "AVISO", 0);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "A Tabela está Vazia, é impossível deletar algo", "AVISO", 0);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ares;
    private javax.swing.JTextField BTU;
    private javax.swing.JTextField Cor;
    private javax.swing.JSpinner Garantia;
    private javax.swing.JTextField Gas;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Modelo;
    private javax.swing.JComboBox<String> Voltagem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
